version: '3.8'
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 8Fny?aXEFkh9ePA3
    networks:
    - infra

  pokedex-back:
    image: pokedex
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - DJANGO__POSTGRES_HOST=postgresql
      - DJANGO__int__POSTGRES_PORT=5432
    networks:
    - infra
    depends_on:
      - postgresql
    ports:
      - '8030:8030'

networks:
  infra:
    name: infra-devio
