# Generated by Django 3.2.12 on 2023-01-17 13:48
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("favorite_object", "0001_initial"),
        ("pokemon", "0002_rename_surname_pokemon_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="favorite_object",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="favorite_object.favoriteobject",
            ),
        ),
    ]
