# Generated by Django 3.2.12 on 2023-01-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('pokemon', '0003_pokemon_favorite_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_team', to='teams.team'),
        ),
    ]
