# Generated by Django 3.2.12 on 2023-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemon_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='team_pk',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='team',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
