# Generated by Django 3.2.12 on 2023-02-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20230205_1742'),
        ('pokemon', '0005_auto_20230127_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='team_pk',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
