# Generated by Django 3.2.12 on 2023-01-17 13:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("favorite_object", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteobject",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
