# Generated by Django 3.2.12 on 2023-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_object', '0002_alter_favoriteobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteobject',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
